### ISSUE TITLE
an example for model

### ISSUE THREAD

**Issue by yunqy** [albanie/convnet-burden#1]
Hi, albanie,
Can I have an example of your matlab model file?
Thank you very much.

**Comment by albanie** [comment]
Hi @yunqy, the first classification model listed [here](https://github.com/albanie/convnet-burden/blob/master/compute_burdens.m#L41) can be downloaded from the [matconvnet homepage](http://www.vlfeat.org/matconvnet/pretrained/) (the link for the model is http://www.vlfeat.org/matconvnet/models/imagenet-matconvnet-alex.mat)

**Comment by yunqy** [comment]
Thank you for your information @albanie, 
hovever can't find deeplab-vggvd-v2 model file on  matconvnet homepage. Can I have the link to your deeplab model?

**Comment by albanie** [comment]
The deeplab model can be found [here](http://www.robots.ox.ac.uk/~albanie/mcn-models.html)
