### ISSUE TITLE
about  feauture memory and GFLOPS.

### ISSUE THREAD

**Issue by yqNLP** [albanie/convnet-burden#10]
> For present 18:
Flops: 2 GFLOPs, feature memory=3GB

> For mcn-mobilenet:
Flops: 579 MFLOPs, feature memory=5GB

And the question is why mobilenet get smaller flops, but with larger feature  memory. What's the relationship between FLOPS and feature memory?

**Comment by albanie** [comment]
MobileNet makes heavy use of group convolutions, which restrict the interactions between channels.  These significantly reduce flops, but not memory usage.

**Comment by yqNLP** [comment]
Thanks.
